import { getRefs } from './js/refs';
import { SStorage } from './js/storage/sessionStorage';
import { onClickLogoLibrary } from './js/renderMarkupFilmoteka/onClickLogoLibrary';
import { changeMode } from './js/changeMode/changeMode';
import { buttonUp } from './js/scroll/button-up';
import { loginModal } from './js/firebaseFilm/loginModal';
import { needRegisterShow, needRegisterHide } from './js/errors/needRegister';
import { renderMarkupLibraryQ } from './js/renderMarkupLibrary/renderMarkupLibraryQ';
import { renderMarkupLibraryW } from './js/renderMarkupLibrary/renderMarkupLibraryW';
import { libraryFirstOpen } from './js/renderMarkupLibrary/renderMarkupLibraryW';
import { renderLogin } from './js/renderLogin/renderLogin';
import toggleModalLibrary from './js/modals/modal-library';
