export const poster_sizes = [
  'w92',
  'w154',
  'w185',
  'w342',
  'w500',
  'w780',
  'original',
];
export const genres_en = [
  {
    id: 28,
    name_en: 'Action',
    name_ru: 'боевик',
    name_ua: 'Бойовик',
  },
  {
    id: 12,
    name_en: 'Adventure',
    name_ru: 'приключения',
    name_ua: 'Пригоди',
  },
  {
    id: 16,
    name_en: 'Animation',
    name_ru: 'мультфильм',
    name_ua: 'Мультфільм',
  },
  {
    id: 35,
    name_en: 'Comedy',
    name_ru: 'комедия',
    name_ua: 'Комедія',
  },
  {
    id: 80,
    name_en: 'Crime',
    name_ru: 'криминал',
    name_ua: 'Кримінал',
  },
  {
    id: 99,
    name_en: 'Documentary',
    name_ru: 'документальный',
    name_ua: 'Документальний',
  },
  {
    id: 18,
    name_en: 'Drama',
    name_ru: 'драма',
    name_ua: 'Драма',
  },
  {
    id: 10751,
    name_en: 'Family',
    name_ru: 'семейный',
    name_ua: 'Сімейний',
  },
  {
    id: 14,
    name_en: 'Fantasy',
    name_ru: 'фэнтези',
    name_ua: 'Фентезі',
  },
  {
    id: 36,
    name_en: 'History',
    name_ru: 'история',
    name_ua: 'Історичний',
  },
  {
    id: 27,
    name_en: 'Horror',
    name_ru: 'ужасы',
    name_ua: 'Жахи',
  },
  {
    id: 10402,
    name_en: 'Music',
    name_ru: 'музыка',
    name_ua: 'Музика',
  },
  {
    id: 9648,
    name_en: 'Mystery',
    name_ru: 'детектив',
    name_ua: 'Детектив',
  },
  {
    id: 10749,
    name_en: 'Romance',
    name_ru: 'мелодрама',
    name_ua: 'Мелодрама',
  },
  {
    id: 878,
    name_en: 'Science Fiction',
    name_ru: 'фантастика',
    name_ua: 'Фантастика',
  },
  {
    id: 10770,
    name_en: 'TV Movie',
    name_ru: 'телевизионный фильм',
    name_ua: 'Телефільм',
  },
  {
    id: 53,
    name_en: 'Thriller',
    name_ru: 'триллер',
    name_ua: 'Трилер',
  },
  {
    id: 10752,
    name_en: 'War',
    name_ru: 'военный',
    name_ua: 'Військовий',
  },
  {
    id: 37,
    name_en: 'Western',
    name_ru: 'вестерн',
    name_ua: 'Вестерн',
  },
];
